"""
Test Script - Leave Request System
Kiểm tra tính năng yêu cầu nghỉ phép
"""
from app.database.connection import create_connection
from app.database.leave_request_queries import LeaveRequestQueries
from app.controllers.leave_request_controller import LeaveRequestController


def test_database_connection():
    """Test 1: Kiểm tra kết nối database"""
    print("=" * 60)
    print("TEST 1: Kiểm tra kết nối database")
    print("=" * 60)
    try:
        conn = create_connection()
        cursor = conn.cursor()
        cursor.execute("SELECT COUNT(*) FROM leave_requests")
        count = cursor.fetchone()[0]
        cursor.close()
        conn.close()
        print(f"✅ Kết nối thành công! Hiện có {count} yêu cầu trong DB")
        return True
    except Exception as e:
        print(f"❌ Lỗi kết nối: {e}")
        return False


def test_table_structure():
    """Test 2: Kiểm tra cấu trúc bảng"""
    print("\n" + "=" * 60)
    print("TEST 2: Kiểm tra cấu trúc bảng leave_requests")
    print("=" * 60)
    try:
        conn = create_connection()
        cursor = conn.cursor()
        cursor.execute("DESCRIBE leave_requests")
        columns = cursor.fetchall()
        
        print("\nCác cột trong bảng:")
        for col in columns:
            print(f"  - {col[0]:15} | {col[1]:30} | Null: {col[2]}")
        
        cursor.close()
        conn.close()
        print("\n✅ Cấu trúc bảng OK!")
        return True
    except Exception as e:
        print(f"❌ Lỗi: {e}")
        return False


def test_create_request():
    """Test 3: Tạo yêu cầu nghỉ phép mới"""
    print("\n" + "=" * 60)
    print("TEST 3: Tạo yêu cầu nghỉ phép TEST")
    print("=" * 60)
    
    controller = LeaveRequestController()
    
    # Tạo yêu cầu test
    success, message = controller.create_request(
        employee_id=1,  # Giả sử employee ID = 1 tồn tại
        leave_type="Nghỉ phép năm",
        start_date_str="2025-12-01",
        end_date_str="2025-12-03",
        reason="Test tính năng yêu cầu nghỉ phép - Auto generated by test script"
    )
    
    if success:
        print(f"✅ {message}")
        return True
    else:
        print(f"❌ {message}")
        return False


def test_get_requests():
    """Test 4: Lấy danh sách yêu cầu"""
    print("\n" + "=" * 60)
    print("TEST 4: Lấy danh sách yêu cầu của employee_id=1")
    print("=" * 60)
    
    controller = LeaveRequestController()
    requests = controller.get_my_requests(employee_id=1)
    
    print(f"\nTìm thấy {len(requests)} yêu cầu:")
    
    for i, req in enumerate(requests[:5], 1):  # Chỉ hiển thị 5 yêu cầu đầu
        print(f"\n  [{i}] ID: {req['id']}")
        print(f"      Loại: {req['leave_type_display']}")
        print(f"      Từ: {req['start_date']} → {req['end_date']}")
        print(f"      Số ngày: {req['total_days']}")
        print(f"      Trạng thái: {req['status_display']}")
        print(f"      Lý do: {req['reason'][:50]}...")
    
    if len(requests) > 5:
        print(f"\n  ... và {len(requests) - 5} yêu cầu khác")
    
    print(f"\n✅ Lấy danh sách thành công!")
    return True


def test_validation():
    """Test 5: Kiểm tra validation"""
    print("\n" + "=" * 60)
    print("TEST 5: Kiểm tra validation")
    print("=" * 60)
    
    controller = LeaveRequestController()
    
    # Test 5.1: Thiếu thông tin
    print("\n[5.1] Test thiếu thông tin:")
    success, message = controller.create_request(
        employee_id=1,
        leave_type="Nghỉ phép năm",
        start_date_str="",
        end_date_str="2025-12-01",
        reason="Test"
    )
    print(f"  {'✅' if not success else '❌'} {message}")
    
    # Test 5.2: Lý do quá ngắn
    print("\n[5.2] Test lý do quá ngắn:")
    success, message = controller.create_request(
        employee_id=1,
        leave_type="Nghỉ phép năm",
        start_date_str="2025-12-01",
        end_date_str="2025-12-01",
        reason="Ngắn"
    )
    print(f"  {'✅' if not success else '❌'} {message}")
    
    # Test 5.3: Ngày không hợp lệ
    print("\n[5.3] Test định dạng ngày sai:")
    success, message = controller.create_request(
        employee_id=1,
        leave_type="Nghỉ phép năm",
        start_date_str="01-12-2025",  # Sai định dạng
        end_date_str="2025-12-01",
        reason="Lý do hợp lệ dài hơn 10 ký tự"
    )
    print(f"  {'✅' if not success else '❌'} {message}")
    
    # Test 5.4: Start > End
    print("\n[5.4] Test ngày bắt đầu > ngày kết thúc:")
    success, message = controller.create_request(
        employee_id=1,
        leave_type="Nghỉ phép năm",
        start_date_str="2025-12-10",
        end_date_str="2025-12-01",
        reason="Lý do hợp lệ dài hơn 10 ký tự"
    )
    print(f"  {'✅' if not success else '❌'} {message}")
    
    # Test 5.5: Ngày quá khứ
    print("\n[5.5] Test ngày trong quá khứ:")
    success, message = controller.create_request(
        employee_id=1,
        leave_type="Nghỉ phép năm",
        start_date_str="2020-01-01",
        end_date_str="2020-01-05",
        reason="Lý do hợp lệ dài hơn 10 ký tự"
    )
    print(f"  {'✅' if not success else '❌'} {message}")
    
    print("\n✅ Tất cả validation hoạt động đúng!")
    return True


def show_summary():
    """Hiển thị tổng kết"""
    print("\n" + "=" * 60)
    print("📊 TỔNG KẾT")
    print("=" * 60)
    
    try:
        conn = create_connection()
        cursor = conn.cursor(dictionary=True)
        
        # Tổng số yêu cầu
        cursor.execute("SELECT COUNT(*) as total FROM leave_requests")
        total = cursor.fetchone()['total']
        
        # Số yêu cầu theo trạng thái
        cursor.execute("""
            SELECT status, COUNT(*) as count 
            FROM leave_requests 
            GROUP BY status
        """)
        status_counts = cursor.fetchall()
        
        print(f"\n📋 Tổng số yêu cầu: {total}")
        print("\nPhân bố theo trạng thái:")
        for stat in status_counts:
            status_map = {
                'pending': '🟠 Chờ duyệt',
                'approved': '🟢 Đã duyệt',
                'rejected': '🔴 Đã từ chối'
            }
            status_text = status_map.get(stat['status'], stat['status'])
            print(f"  {status_text}: {stat['count']}")
        
        cursor.close()
        conn.close()
        
    except Exception as e:
        print(f"❌ Lỗi: {e}")


if __name__ == "__main__":
    print("\n" + "🧪" * 30)
    print("   LEAVE REQUEST SYSTEM - TEST SUITE")
    print("🧪" * 30)
    
    # Chạy các test
    test_database_connection()
    test_table_structure()
    test_create_request()
    test_get_requests()
    test_validation()
    show_summary()
    
    print("\n" + "✅" * 30)
    print("   HOÀN THÀNH TẤT CẢ TEST!")
    print("✅" * 30 + "\n")
